version: '3.1'
services:
  stats-server:
    build: ./stat-service/server
    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - STRING_DATASOURCE_USERNAME=ewm
      - STRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm